version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest

    steps:
      - checkout

      - restore_cache:
          keys:
          - deps-{{ checksum "examples/package.json" }}-{{ checksum "examples/packages.dhall" }}

      - run:
          command: |
            git checkout -b gh-pages
            git reset --hard origin/master

      - run:
          working_directory: examples
          command: |
            yarn add --dev purescript spago parcel
            yarn
            yarn build

      - save_cache:
          paths:
            - examples/node_modules
            - examples/.spago
            - output
          key: deps-{{ checksum "examples/package.json" }}-{{ checksum "examples/packages.dhall" }}

      - run:
          command: |
            cp docs/* .
            git config user.email "remotenonsense@gmail.com"
            git config user.name "CircleCI"
            git add . && git commit -am 'build gh-pages'
            # https://stackoverflow.com/a/48763205
            git push -q -f https://${GH_PAGES_TOKEN}@github.com/nonbili/purescript-halogen-nselect.git gh-pages

workflows:
  version: 2
  build-gh-pages:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
